[google_credentials]
type = "service_account"
project_id = "lockinai-456205"
private_key_id = "3a680e819d2493b7006f2c7989d2dc0a0fb80c72"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDvPipSUU4/Ut9v
NkzTtVCoiBVdcaOS2oKVtpn1Dy7yISfXiWuDL6vX+GvbT2MYxv8fk0JolytfOlqx
eRsNphWQAZJEzIJE2KTu41AWNQI7xnc4eme5snmhiumQXBtGVo7vmqWhpadQTl85
zXZySy62iKTz8gHDrvGjhx53or5eOFW+dYB+AN2Gm7Upe/T74IdDweDmHqZVAkPv
ktZJ/uv65/FpLJ6GII4iF8uZyJXe9b1SskkTi2f61oZM47g3s/PKhhExjUvuVUcU
QTk8ocWuWQBe3CmmsUJUKvdhuUYC7QdSBhg36NV/iHxL8aoXmpiDJxO4ELqT/j0O
c+BLkShlAgMBAAECggEANXj3jJ6Plqe3OOwyD7+e34xK+i/EF7avKTc/Af76xzOR
7CLS3OdyyTrFIKeFxqvzqeMIHMhs8UPhsXkYCtzsRNuVDbuIAktJ0fsMk2oVrbaW
PxFczayOcwTRX2q2zena2ML/8jlMRC7AKfM6XiFft3yjIcMdkdcwOxSgQq0lT3lp
Tcm9ChNbRoeENB5UAznnjKEa+pTk2SS9wflPWSYO1At1BBaKw0PLakY7Bm54tw12
Ojk9d8bZpv7+hDdQisnr+iwwwhIPWiFeqcxcl8whN+hOGn0h4CEcFoDKxVItQkwR
on53CdbdjZdssnWcpOacJdASria8QhpUPbMRB2q0oQKBgQD6cuuK3CyY/d5BxOzF
pxZXt6SCJgP31RJiId3aeG8Sjos2hpp2QCWuS9GcOjvdQA6wDWGz9Nun4PftxrVF
9FDI9/XLYEvSX/G1cl680VNxYRsdwNh5naw1+rXxKwtpdNUN4zwPM83PK8wMxrVW
OOYcnfO2OdvwhaYtb/yTga14HwKBgQD0i6kWs5QjpRLUXEQaMSxtOyaazl4VBJfR
d7zKSAerqtG8blKzovtRHs8cRuqNLoYReH8BmRag9ck/aAT6Z9X59KziKQKIlTor
gzZnGD5fapN8gQQrrc8Blyt1rbbnha58Uvbjil0q4Wu5B6RdeSSYwnPzZ6vedEsW
VGBkg39e+wKBgBoCUT/Meb0xsCE4aDZmkcVuRuFVPVhBgnU6eyWzGCXfM8nn1Kav
JrqhGRWWXp0th9j0qs7bgOxASr8gwbaQFsuoJJiIWZdxa1KinAAT5QyDPyOp4VFP
9JBuhvKSu86p2W5lyNjzUk5PiBNTl4Vqx0r1hFfKTnL+DjHtzVcsQm2VAoGBAMwB
6si+fToTTxcL9eBn32ksrHL+8CvWjhS4MC4MUyHaOmhZHPMxZzlwW1V6r9eh1USj
4khh/ye+g+o6i9SeZTrF7KgrkCqDW2jLaMouxnHxRiLaurD5qbTo+N+OUQTqV/rt
d3uxhTHtpmFQx8UW9/ncVsDbXt0Q5Uc2ksenj82bAoGBAPZzVmU02BcQA3LOJ1qa
NE4VGj2muxPVp+A23L3qqgT6YeJ3FYYPRgsToY99ye5CXIB8KMPIMybwIN0THbVi
sInNIruMnHkfo4gghpyYt5780H0OZ3NTDt1rEPAGJNNgy4VKpHB9cJm17LlAiVa0
2EpHmA5gDll6AWTjquKcJg7D
-----END PRIVATE KEY-----"""
client_email = "lockinacc@lockinai-456205.iam.gserviceaccount.com"
client_id = "112817195907307015968"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/lockinacc%40lockinai-456205.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
